language: node_js

node_js:
  - "5"

before_script:
  - cd ..
  - pwd
  - git clone https://github.com/o2platform/leanpub-book-site.git
  - ls -la
  - cd leanpub-book-site
  - ./set-up.sh
  - ls -la
  - npm install

script:
  - ./bin/Create-Book.coffee
  - cd book
  - ls -la

after_script:
  - echo ">>>>> Updating Build repo <<<<<"
  - git config --global user.email "bot@travis.com"
  - git config --global user.name "Travis Bot"

  - cd Book_Practical_AngularJS_Build
  - git add -A
  - git commit -m 'commiting manuscript changes'
  - git push origin master