language: node_js

node_js:
  - "5"

before_script:
  - cd ..
  - pwd
  - git clone https://github.com/o2platform/leanpub-book-site.git
  - ls -la
  - cd leanpub-book-site
  - ./set-up.sh
  - ls -la
  - ./bin/Create-Book.coffee
  - cd book
  - ls -la