language: node_js

node_js:
  - "5"

env:
  global:
    - secure: "ISzpFEy7c5rxQoA/wrVCIfVwDvGrzFG1Fx+dzUIUt2q8HyPOuOuwHt1eVfH94/Zn/hEPuaPUaoFxpYPs3xpZCsl16bFAJLeuWDguYCw2DzgsVHVhXSSELtFqtg/Hd5Coq51s1Wj74Ril7o/sJ2efkaQC3BaowZZxAImpJR9Iyj4="


before_script:
  - cd ..
  - pwd
  - git clone https://github.com/o2platform/leanpub-book-site.git
  - ls -la
  - cd leanpub-book-site
  - ./set-up.sh
  - ls -la
  - npm install

script:
  - ./bin/Create-Book.coffee
  - cd book
  - ls -la

  - echo ">>>>> Updating Build repo <<<<<"
  - git config --global user.email "bot@travis.com"
  - git config --global user.name "Travis Bot"

  - cd Book_Practical_AngularJS_Build
  - git remote set-url origin https://DinisCruz-Dev:$git_pwd@github.com/DinisCruz-Dev/Book_Practical_AngularJS_Build.git
  - git add -A
  - git commit -m 'commiting manuscript changes'
  - git push origin master